name: Build Executables

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run Tests
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        output_name="tailbone"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          output_name="tailbone.exe"
        fi
        
        # Extract version from the release tag
        VERSION=${GITHUB_REF#refs/tags/}
        # Get the short commit hash
        COMMIT=$(git rev-parse --short HEAD)
        
        mkdir -p dist
        go build -v \
          -ldflags "-X 'utils.Version=${VERSION}' -X 'utils.Commit=${COMMIT}'" \
          -o "dist/${output_name}" ./cmd/keys

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tailbone-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/*
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 